import type { Metadata } from "next";
import localFont from "next/font/local";

import { cookies } from "next/headers";
import { UIThemeProvider } from "@repo/ui/themes/themeProvider";
import DefaultLayout from "@repo/ui/layout/DefaultLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const c = await cookies();
  const mode = (c.get("theme")?.value as "light" | "dark") ?? "light";
  return (
    <html lang="ko">
      <body>
        {/* <UIThemeProvider initialMode={mode}> */}
        <DefaultLayout initialMode={mode}>{children}</DefaultLayout>
        {/* </UIThemeProvider> */}
      </body>
    </html>
  );
}
