import type { Metadata } from "next";
import localFont from "next/font/local";

import { cookies } from "next/headers";
import { UIThemeProvider } from "@repo/ui/themes/themeProvider";
import DefaultLayout from "@repo/ui/layout/DefaultLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const c = await cookies();
  const mode = (c.get("theme")?.value as "light" | "dark") ?? "light";
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <UIThemeProvider initialMode={mode}> */}
        <DefaultLayout initialMode={mode}>{children}</DefaultLayout>
        {/* </UIThemeProvider> */}
      </body>
    </html>
  );
}
