import type { Metadata } from "next";

import { cookies } from "next/headers";
import StyledComponentsRegistry from "../components/StyledComponentsRegistry";
import DefaultLayout from "@repo/ui/layout/DefaultLayout";
import ThemeToggle from "@repo/ui/themes/themeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const mode = (cookie.get("theme")?.value as "light" | "dark") ?? "dark";
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <DefaultLayout
            initialMode={mode}
            headerContent={<ThemeToggle />}
            maxWidth={{
              web: 90,
              tablet: 90,
              mobile: "100%",
            }}
          >
            {children}
          </DefaultLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
