import type { Metadata } from "next";

import { cookies } from "next/headers";
import StyledComponentsRegistry from "../components/StyledComponentsRegistry";
import BlogLayout from "@repo/ui/layout/blog/BlogLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const mode = (cookie.get("theme")?.value as "light" | "dark") ?? "dark";
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <BlogLayout initialMode={mode}>{children}</BlogLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
