export const REABLE_HOMEPAGE_STACKS = [
  "TypeScript",
  "Next.js",
  "NestJS",
  "Zustand",
  "Radix UI",
  "Tailwind CSS",
  "RestAPI",
  "Axios",
  "AWS EC2",
  "AWS S3",
  "AWS Lambda",
  "Nx Monorepo",
  "pnpm",
  "i18next",
];
export const SAVEE_STACKS = [
  "TypeScript",
  "Next.js",
  "Zustand",
  "Styled-Components",
  "RestAPI",
  "Axios",
  "AWS EC2",
  "HighCharts",
  "i18next",
];
export const NZT_STACKS = [
  "TypeScript",
  "Next.js",
  "Zustand",
  "Emotion",
  "RestAPI",
  "Axios",
  "AWS EC2",
  "HighCharts",
  "i18next",
  "jest",
];
export const CODE_EDITOR_STACKS = [
  "TypeScript",
  "Next.js",
  "Emotion",
  "RestAPI",
  "Axios",
  "AWS EC2",
  "Monaco Editor",
  "Socket IO",
  "AgoraRTC",
  "Vimeo",
];
export const DING_CO_STACKS = [
  "TypeScript",
  "Next.js",
  "Recoil",
  "Emotion",
  "Antd",
  "Material UI",
  "GraphQL",
  "Apollo Client",
  "AWS EC2",
  "AWS S3",
  "Toast UI Editor",
  "Vimeo",
];
export const NEW_BIZ_START_STACKS = [
  "TypeScript",
  "Next.js",
  "React Context",
  "Emotion",
  "Antd",
  "GraphQL",
  "Apollo Client",
  "AWS EC2",
  "AWS S3",
  "Toast UI Editor",
  "Vimeo",
];
